profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'



urlpatterns = [
    path('my-profile/', views.my_profile_view, name='my-profile'),
    path('all-profiles/', views.ProfileListView.as_view(), name='all_profiles'),
    path('profile/<slug>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('send-invite/', views.send_invitation, name='send-invite'),
    path('invites/', views.invites_received_view, name='invites'),
    path('invites/accept/', views.accept_invitation, name='accept-invite'),
    path('invites/reject/', views.reject_invitation, name='reject-invite'),
    path('remove-friend/', views.remove_from_friends, name='remove-friend')
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db.models import Q
import uuid


class ProfileManager(models.Manager):
    def get_all_profiles_to_invite(self, sender):
        '''
        友達申請するユーザー情報 (まだ友達ではないユーザー)
        '''
        profiles = Profile.objects.all().exclude(user=sender)  # senderは自分（request.user）
        profile = Profile.objects.get(user=sender)  # 自分（request.user）
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        
        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':  # 送るは、not acceptなのでどちらかがacceptだった場合、両者accepted.
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)
        
        available = [profile for profile in profiles if profile not in accepted]  # まだ友達ではないユーザー
        print(available)
        return available
    
    def get_all_profiles_without_me(self, me):
        '''
        自分以外のユーザー情報
        '''
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    '''
    プロフィールモデル
    '''
    first_name = models.CharField('姓', max_length=200, blank=True)
    last_name = models.CharField('名', max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="よろしくお願いします。", max_length=300)
    email = models.EmailField(max_length=200, blank=True)   
    avatar = models.ImageField(default='avatar.png', upload_to='avatars') 
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = ProfileManager()
    
    def __str__(self):
        return self.user.username
    
    def get_absolute_url(self):
        '''
        Modelの詳細ページのURLを返す
        '''
        return reverse('profiles:profile-detail', kwargs={'slug': self.slug})
    
    
    def get_friends(self):
        '''
        全ての友達
        '''
        return self.friends.all()
    
    def get_friends_count(self):
        '''
        友達の数
        '''
        return self.friends.all().count()
    
    def get_posts_count(self):
        '''
        投稿の数
        '''
        return self.posts.all().count()     

    def get_all_authors_posts(self):
        '''
        全ての投稿
        '''
        return self.posts.all()
    
    def get_likes_given_count(self):
        '''
        全ての投稿の与えたいいね数
        '''
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked += 1
        return total_liked
    
    def get_likes_recieved_count(self):
        '''
        全ての投稿の受け取ったいいね数
        '''
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked
    

    def save(self, *args, **kwargs):
        self.slug = str(uuid.uuid4())[:6]
        ex = Profile.objects.filter(slug=self.slug).exists()
        while ex:
            self.slug = str(uuid.uuid4())[:6]
            ex = Profile.objects.filter(slug=self.slug).exists()
        return super().save(*args, **kwargs)

    
STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        '''
        申請を承認するユーザー（acceptする前の状態）
        '''
        qs = Relationship.objects.filter(receiver=receiver, status='send')  
        return qs
    

class Relationship(models.Model):
    '''
    関係性モデル
    '''
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(choices=STATUS_CHOICES, max_length=8)   
    updated = models.DateTimeField(auto_now=True) 
    created = models.DateTimeField(auto_now_add=True)
    
    objects = RelationshipManager()
    
    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"
    
    
    

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')



        
    

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from .models import Profile, Relationship
from .forms import ProfileModelForm


@login_required
def my_profile_view(request):
    '''
    自分のプロフィール情報
    '''
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    
    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm
    }
    return render(request, 'profiles/my_profile.html', context)


class ProfileListView(LoginRequiredMixin, ListView):
    '''
    自分以外のユーザーを一覧表示
    '''
    model = Profile
    template_name = 'profiles/profile_list.html'
    
    def get_queryset(self):
        '''
        自分以外の情報取得
        '''
        qs = Profile.objects.get_all_profiles_without_me(self.request.user)
        return qs  # object_list
    
    def get_context_data(self, **kwargs):
        '''
        友達申請したユーザー、友達申請してきたユーザー名を取得
        '''
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=str(self.request.user))
        profile = Profile.objects.get(user=user)  # 自分のプロフィール
        rel_r = Relationship.objects.filter(sender=profile)  # 申請した相手の情報
        rel_s = Relationship.objects.filter(receiver=profile)  # 申請してきた相手の情報
        rel_receiver = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)  # ユーザー名だけ取り出す
        rel_sender = []
        for item in rel_s:
            rel_sender.append(item.sender.user)
            
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        
        if len(self.get_queryset()) == 0:  # 自分以外ユーザーが存在しない場合
            context['is_empty'] = True
        return context


class ProfileDetailView(LoginRequiredMixin, DetailView):
    '''
    特定のユーザーの情報
    return (
        rel_receiver: 申請したユーザーのユーザー名
        rel_sender: 申請してきたユーザーのユーザー名
        posts: そのユーザーの全ての投稿 
        len_posts: そのユーザーの投稿があるかどうか（真偽値）
    )
    '''
    model = Profile
    template_name = 'profiles/profile_detail.html'
    
    def get_object(self):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)  # slugから特定のユーザーを取得
        return profile
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=str(self.request.user))
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        rel_sender = []
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context
 
        
@login_required        
def send_invitation(request):
    '''
    友達申請をする（sendする）
    '''
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')  # send状態の関係性を作る
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')


@login_required
def invites_received_view(request):
    '''
    友達申請の受け取り
    '''
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)  # 友達申請をしてきたが、まだ承認していないユーザー
    results = list(map(lambda x: x.sender, qs))  # 送り主の情報だけ取得
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'qs': results,
        'is_empty': is_empty
    }
    return render(request, 'profiles/invites.html', context)


@login_required
def accept_invitation(request):
    '''
    友達申請を承認する
    '''
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:invites')

@login_required
def reject_invitation(request):
    '''
    友達申請を拒否する
    '''
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:invites')


@login_required
def remove_from_friends(request):
    '''
    友達を解除する
    '''
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()  # 一方的に友達解除する
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:all_profiles')
    
            

profiles/templates/profiles/invites.html
{% extends 'base.html' %}

{% block title %}
Invitation
{% endblock title %}


{% block content %}

{% if is_empty %}
    <div class="alert alert-warning" role="alert">
        <h1 class="text-center">現在、友達申請はありません。</h1>
    </div>
{% endif %}


    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            {% for obj in qs %}
            <div class="col-md-8 mb-3">
                <div class="card shadow-lg rounded">
                    <div class="card-body">
                        <div class="row text-center align-items-center">
                            <div class="col-md-3">
                                <img class="p_avatar" src="{{ obj.avatar.url }}" alt="">
                            </div>
                            <div class="col-md-5">
                                <span class="text-muted">ユーザー名：</span>
                                <h3>{{ obj.user }}</h3>
                            </div>
                            <div class="col-md-2">
                                <form action="{% url 'profiles:accept-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="btn btn-outline-success"><i class="fa fa-check"></i>&nbsp;承認する</button>
                                </form>
                            </div>
                            <div class="col-md-2">
                                <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="btn btn-outline-danger"><i class="fa fa-times"></i>&nbsp;拒否する</button>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

profiles/templates/profiles/my_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
My Profile
{% endblock title %}


{% block content %}


<!-- Modal -->
<div class="modal fade" id="myprofileModal" tabindex="-1" role="dialog" aria-labelledby="myprofileModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content mt-3">
      <div class="modal-header">
        <h5 class="modal-title" id="myprofileModalLabel">プロフィール編集</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" class="mx-5" enctype='multipart/form-data'>
          {% csrf_token %}
          <div class="form-label-group">
            {% render_field form.first_name class='form-control' placeholder='姓' %}
          </div>
          <div class="form-label-group">
            {% render_field form.last_name class='form-control' placeholder='名' %}
          </div>
          <div class="form-label-group">
            {% render_field form.bio class='form-control' placeholder='自己紹介' %}
          </div>
          <div class="form-label-group">
            {% render_field form.avatar class='form-control' %}
          </div>
          <hr>
          <div class="button mx-auto">
            <button class="btn btn-lg btn-outline-warning btn-block mx-auto" type="submit">更新する</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


<div class="container-fluid mt-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card shadow-lg rounded">
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-5 text-center my-3">
              <img class="p_avatar" src="{{ profile.avatar.url }}" alt="">
              <div class="mt-5">
                <button class="btn btn-lg btn-outline-secondary" data-toggle="modal"
                  data-target="#myprofileModal">プロフィールを編集する</button>
              </div>
            </div>
            <div class="col-12 col-md-7">
              <table class="table">
                <tbody>
                  <tr>
                    <th scope="row">ユーザー名</th>
                    <td>{{ profile.user }}</td>
                  </tr>
                  <tr>
                    <th scope="row">姓</th>
                    <td>{{ profile.first_name }}</td>
                  </tr>
                  <tr>
                    <th scope="row">名</th>
                    <td>{{ profile.last_name }}</td>
                  </tr>
                  <tr>
                    <th scope="row">自己紹介</th>
                    <td>{{ profile.bio }}</td>
                  </tr>
                  <tr>
                    <th scope="row">友達の数</th>
                    <td>{{ profile.get_friends_count }}人</td>
                  </tr>
                  <tr>
                    <th scope="row">友達</th>
                    <td>
                      {% for friend in profile.get_friends %}
                      {{ friend }}、
                      {% endfor %}
                    </td>
                  </tr>
                  <tr>
                    <th scope="row">投稿の数</th>
                    <td>{{ profile.get_posts_count }}</td>
                  </tr>
                  <tr>
                    <th scope="row">いいねした数</th>
                    <td>{{ profile.get_likes_given_count }}</td>
                  </tr>
                  <tr>
                    <th scope="row">いいねされた数</th>
                    <td>{{ profile.get_likes_recieved_count }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock title %}


{% block content %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      {% if object.avatar %}
      <img class="img-thumbnail d_avatar" src="{{ object.avatar.url }}" alt="">
      {% endif %}
      <div>
        <h1>{{ object.user }}</h1>
        <table class="table">
          <tbody>
            <tr>
              <td scope="row">友達の数</td>
              <td>{{ object.get_friends_count }}</td>
            </tr>
            <tr>
              <td scope="row">投稿の数</td>
              <td>{{ object.get_posts_count }}</td>
            </tr>
            <tr>
              <td scope="row">いいねした数</td>
              <td>{{ object.get_likes_given_count }}</td>
            </tr>
            <tr>
              <td scope="row">いいねをもらった数</td>
              <td>{{ object.get_likes_recieved_count }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-12 col-md-6">
      {% for post in posts %}
      <div class="card mb-3 shadow rounded">
        <div class="card-header">
          <p class="card-text"><small class="text-muted">{{ post.created|timesince}}前</small></p>
        </div>
        {% if post.image %}
        <img class="card-img-top" src="{{ post.image.url }}" alt="">
        {% endif %}
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
User
{% endblock title %}

<!-- 
object_list: 自分以外の全てのユーザー
rel_receiver: 申請先のユーザー
rel_sender: 申請してきたユーザー
 -->


{% block content %}

    {% if is_empty %}
        <div class="alert alert-warning" role="alert">
            <h1 class="text-center">現在、他のユーザーはいません。</h1>
        </div>
    {% endif %}

    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            {% for obj in object_list %}
            <div class="col-md-8 mb-3">
                <div class="card shadow-lg rounded">
                    <div class="card-body">
                        <div class="row text-center align-items-center">
                            <div class="col-md-3">
                                <img class="p_avatar" src="{{ obj.avatar.url }}" alt="">
                            </div>
                            <div class="col-md-5">
                                <span class="text-muted">ユーザー名：</span>
                                <h3>{{ obj.user }}</h3>
                            </div>
                            <div class="col-md-2">
                                <a href={{obj.get_absolute_url}}>
                                    <button class="btn btn-success px-2"><i class="fa fa-search-plus"></i> もっと見る</button>
                                </a>
                            </div>
                            <div class="col-md-2">
                                {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                                <form action="{% url 'profiles:send-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="btn btn-outline-primary"><i class="fa fa-user-plus"></i>&nbsp;友達申請</button>
                                </form>
                                {% endif %}
                                {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                                    <button type="submit" class="btn btn-outline-secondary disabled" aria-disabled="true">承認待ち</button>
                                {% endif %}
                                {% if request.user in obj.friends.all %}
                                    <form action="{% url 'profiles:remove-friend' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                        <button type="submit" class="btn btn-outline-danger"><i class="fa fa-ban"></i>&nbsp;友達解除</button>
                                    </form>

                                {% endif %}

                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    
   
        
    

    


 



{% endblock content %}