accounts/urls.py
from django.urls import path 
from . import views


app_name = 'accounts'


urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.post_comment_create_and_list_view, name='home'),
    path('<pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('<pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('like/', views.like_post, name='like-post'),
]


    

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'



urlpatterns = [
    path('my-profile/', views.my_profile_view, name='my-profile'),
    path('all-profiles/', views.ProfileListView.as_view(), name='all_profiles'),
    path('profile/<slug>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('send-invite/', views.send_invitation, name='send-invite'),
    path('invites/', views.invites_received_view, name='invites'),
    path('invites/accept/', views.accept_invitation, name='accept-invite'),
    path('invites/reject/', views.reject_invitation, name='reject-invite'),
    path('remove-friend/', views.remove_from_friends, name='remove-friend')
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!--Custom css-->
    <link rel="stylesheet" href="{% static 'style.css'%}">


    <title>sns - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock content %}

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/navbar.html
{% url 'posts:home' as path_to_home %}
{% url 'profiles:all_profiles' as path_to_all_profiles %}
{% url 'profiles:invites' as path_to_invites %}
{% url 'profiles:my-profile' as path_to_my_profile %}


<nav class="navbar navbar-expand-lg navbar-light bg-light py-3 shadow rounded">
    <div class="container">
        <a class="navbar-brand" href="#">SNS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="{% if request.path == path_to_home %} nav-item active{% endif %} nav-item">
                    <a class="nav-link" href="{% url 'posts:home' %}"><i class="fa fa-home"></i>&nbsp;ホーム</a>
                </li>
                <li class="{% if request.path == path_to_all_profiles %} nav-item active{% endif %} nav-item">
                    <a class="nav-link" href="{% url 'profiles:all_profiles' %}"><i class="fa fa-users"></i>&nbsp;ユーザー</a>
                </li>
                <li class="{% if request.path == path_to_invites %} nav-item active{% endif %} nav-item">
                    <a class="nav-link" href="{% url 'profiles:invites' %}">
                        <i class="fa fa-user-plus"></i>
                        友達申請
                        <span class="badge badge-light font-weight-bold text-danger">{{ invites_count }}</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="{% if request.path == path_to_my_profile %} nav-item active{% endif %} nav-item">
                    <a class="nav-link" href="{% url 'profiles:my-profile' %}">{{ request.user }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">サインアップ</a>
                </li>
                
                {% endif %}
            </ul>

        </div>
    </div>
</nav>