posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.post_comment_create_and_list_view, name='home'),
    path('<pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('<pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('like/', views.like_post, name='like-post'),
]


    

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile


class Post(models.Model):
    '''
    投稿モデル
    '''
    content = models.TextField()
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')  # いいねは、他人のプロフィール
    author = models.ForeignKey(Profile, related_name='posts', on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.content[:20])
    
    def num_likes(self):
        return self.liked.all().count()
    
    def num_comments(self):
        return self.comment_set.all().count()
    
    class Meta:
        ordering = ('-created',)    
    



class Comment(models.Model):
    '''
    コメントモデル
    '''
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)  # 誰が
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # 何を
    body = models.TextField(max_length=200)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like', 'いいね'),
    ('Unlike', '解除')
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)  # 誰が
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # 何を
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)    
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}--{self.post}--{self.value}"

posts/forms.py
from django import forms
from .models import Post, Comment


class PostModelForm(forms.ModelForm):
    '''
    投稿フォーム
    '''
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))
    class Meta:
        model = Post
        fields = ('content', 'image')
        

class CommentModelForm(forms.ModelForm):
    '''
    コメントフォーム
    '''
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Like
from .forms import PostModelForm, CommentModelForm
from profiles.models import Profile


@login_required
def post_comment_create_and_list_view(request):
    '''
    新規投稿、コメント投稿、一覧表示
    '''
    posts = Post.objects.all()
    profile = Profile.objects.get(user=request.user)
    # 初期設定
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False
    
    if 'submit_p_form' in request.POST:
        print(request.POST)
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile  # 投稿者
            instance.save()
            p_form = PostModelForm()  # 更新
            post_added = True
            
    if 'submit_c_form' in request.POST:
        print(request.POST)
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()
            
    context = {
        'posts': posts,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added
    }
    return render(request, 'posts/home.html', context)
            

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:home')
    
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        # 投稿者本人しか編集できないようにする
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, '権限がありません。')
            return super().form_valid(form)
    

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:home')
    
    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        # 投稿者本人しか編集できないようにする
        if not obj.author.user == self.request.user:
            messages.warning(self.request, '権限がありません。')
        return obj
    

@login_required
def like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)
        
        # 一度しかlikeできない、2回目は解除
        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)
            
        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)
        '''
        like：オブジェクト
        created：真偽値（getの場合false、createの場合true）
        '''
        
        # すでにオブジェクトが存在する場合
        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        # 初めてLikeする場合
        else:
            like.value = 'Like'      
            post_obj.save() 
            like.save() 
        
        data = {
            'value': like.value,
            'likes': post_obj.liked.all().count()
        }    
        return JsonResponse(data, safe=False)
    return redirect('posts:home')
         
                
       
       
                    
       
           
            
     
        
                    
  
                
            
            

posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
Delete
{% endblock title %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>      
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not messages %}


    <div class="card card-auth my-5 mx-auto">
        <div class="card-body">
            <p class="card-title text-center">本当にこの投稿を削除してもよろしいでしょうか？</p>
            <form method="POST" class="form-auth">
                {% csrf_token %}
                <div class="button mx-auto">
                    <button class="btn btn-lg btn-danger btn-block mx-auto" type="submit">削除する</button>
                </div>
            </form>
        </div>
    </div>
    

    {% endif %}

{% endblock content %}

posts/templates/posts/home.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
Home
{% endblock title %}


{% block content %}


<div class="container-fluid mt-4">
    {% if post_added %}
    <div class="alert alert-success text-center" role="alert">
        投稿しました！
    </div>
    {% endif %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-7">
            <div class="button mx-auto" data-toggle="collapse" data-target="#collapse_post" aria-expanded="false"
                aria-controls="collapse_post">
                <button class="btn btn-lg btn-outline-secondary btn-block mx-auto">
                    新規投稿
                </button>
            </div>
            <div class="collapse" id="collapse_post">
                <div class="card">
                    <div class="card-body pb-2">
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div>
                                {% render_field p_form.content class='form-control' %}
                            </div>
                            <div class="my-2">
                                {% render_field p_form.image class='form-control text-muted' %}
                            </div>
                            <hr>
                            <div class="text-center">
                                <button class="btn btn-outline-secondary" type="submit"
                                    name="submit_p_form">投稿する</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% for post in posts %}
            <div class="card my-3 shadow-lg rounded">
                <div class="card-header">
                    <small class="text-muted">{{ post.author.user }} :
                        {{ post.created|timesince}}前</small>
                    <div class="float-right">
                        {% ifequal request.user post.author.user %}
                        <a href="{% url 'posts:post-update' post.pk %}" class="btn">編集</a>
                        <a href="{% url 'posts:post-delete' post.pk %}" class="btn">削除</a>
                        {% endifequal %}
                    </div>
                </div>
                {% if post.image %}
                <img class="card-img-top" src="{{ post.image.url }}" alt="">
                {% endif %}
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-9">
                            <p class="card-text">{{ post.content }}</p>
                            <i class="fa fa-comments-o"></i> <span>{{ post.num_comments }}</span>
                            <i class="fa fa-heart"></i> <span class="like-count{{post.id}}">{{ post.num_likes }}</span>
                        </div>
                        <div class="col-md-3 text-right">
                            <form action="{% url 'posts:like-post' %}" method="POST" class="like-form"
                                id="{{ post.id }}">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{post.id}}>
                                <button type="submit" class="btn btn-outline-danger like-btn{{post.id}}">
                                    {% if profile not in post.liked.all %}
                                    <i class="fa fa-thumbs-up"></i> いいね
                                    {% else %}
                                    <i class="fa fa-thumbs-down"></i> 解除
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-light text-muted" data-toggle="collapse"
                        data-target="#collapse{{post.id}}" aria-expanded="false" aria-controls="collapse{{post.id}}">
                        コメント表示/非表示
                    </button>
                    <div class="collapse" id="collapse{{post.id}}">
                        <ul class="list-group list-group-item-light">
                            {% if post.comment_set.all %}
                            {% for comment in post.comment_set.all %}
                            <li class="list-group-item">
                                <img class="avatar" src={{comment.user.avatar.url}}>
                                <span>{{ comment.user }}</span><br>
                                <p class="my-1">{{ comment.body }}</p>
                            </li>
                            {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{post.id}}>
                        {% render_field c_form.body class='form-control' %}
                        <button type="submit" name="submit_c_form" class="btn btn-primary">送信</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
    $(document).ready(function () {
        $('.like-form').submit(function (e) {
            e.preventDefault()

            const post_id = $(this).attr('id')
            const likeText = $(`.like-btn${post_id}`).text()
            const trim = $.trim(likeText)
            const url = $(this).attr('action')
            let res;
            const likes = $(`.like-count${post_id}`).text()
            const trimCount = parseInt(likes)

            const like = '<i class="fa fa-thumbs-up"></i> いいね'
            const unlike = '<i class="fa fa-thumbs-down"></i> 解除'

            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'post_id': post_id,
                },
                success: function (response) {
                    if (trim === '解除') {
                        $(`.like-btn${post_id}`).html(like)
                        res = trimCount - 1
                    } else {
                        $(`.like-btn${post_id}`).html(unlike)
                        res = trimCount + 1
                    }
                    $(`.like-count${post_id}`).text(res)
                },
                error: function (response) {
                    console.log('error', response)
                }
            })
        })
    })
</script>

{% endblock scripts %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Edit
{% endblock title %}

{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-12 col-md-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-center">投稿編集</h5>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-4">
                        {% render_field form.content class='form-control' %}
                    </div>
                    <div class="my-3">
                        {% render_field form.image class='form-control' %}
                    </div>        
                    <div class="button mx-auto mt-5">
                        <button class="btn btn-lg btn-warning btn-block mx-auto" type="submit">編集する</button>
                    </div>
                </form>
            </div>
        </div>        

    </div>
</div>


{% endblock content %}